project_id = "bvleffevnnugjdwygqyz"

[functions.moneroo-webhook]
verify_jwt = false

[functions.process-moneroo-payment]
verify_jwt = false

[functions.nowpayments-webhook]
verify_jwt = false

[functions.process-nowpayments-payment]
verify_jwt = false

[functions.make-admin]
verify_jwt = false

[functions.retry-payment]
verify_jwt = false

[functions.initiate-payout]
verify_jwt = false