[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# SPA redirect rules
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API proxy for Supabase (optional, pour éviter les CORS)
[[redirects]]
  from = "/api/*"
  to = "https://bvleffevnnugjdwygqyz.supabase.co/:splat"
  status = 200
  force = true

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://www.google-analytics.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https: blob:; connect-src 'self' https://bvleffevnnugjdwygqyz.supabase.co wss://bvleffevnnugjdwygqyz.supabase.co https://www.google-analytics.com; media-src 'self' data: blob:; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'none';"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache fonts
[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "*.ico"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

# Environment variables settings
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"

[context.branch-deploy.environment]
  NODE_ENV = "development"

# Plugin configuration
[[plugins]]
  package = "@netlify/plugin-sitemap"

# Form handling (si vous avez des formulaires)
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true